name: flutter_demo_task
description: A task soluttion.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

#    add translations
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
#   state management, intelligent dependency injection, and route management
  get: ^4.6.5
#  for creating animated badges.
  badges: ^2.0.3
#  easy-to-use method call debouncer
  easy_debounce: ^2.0.2+1
#  play json animations || lottie files
  lottie: ^2.0.0
#  show images from the internet and keep them in the cache directory
  cached_network_image: ^3.2.3
#  Approximate how your app looks on another device
  device_preview: ^1.1.0
#for rendering svg images
  flutter_svg: ^1.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#  auto generate assets
  build_runner:
  flutter_gen_runner:


flutter:

#  auto generate translations message
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/btn_background.png

  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: fonts/Poppins-Thin.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Black.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 900
flutter_intl:
  enabled: true